apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-deployer-admin
  namespace: deployment-automation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-deployer-admin
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: nginx-ingress-deployer-admin
  namespace: deployment-automation
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Using the existing cluster-admin role
  apiGroup: rbac.authorization.k8s.io
