apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-deployer
  namespace: deployment-automation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-deployer
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-deployer
subjects:
- kind: ServiceAccount
  name: nginx-ingress-deployer
  namespace: deployment-automation
roleRef:
  kind: ClusterRole
  name: nginx-ingress-deployer
  apiGroup: rbac.authorization.k8s.io
