controller:
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  replicaCount: 1
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
