name: Deploy NGINX Ingress Controller

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/nginx-ingress-deployer
  KUBE_NAMESPACE: deployment-automation

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      
      - name: Set image output
        id: image
        run: echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          
      - name: Generate Random Suffix
        id: random
        run: echo "suffix=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 5 | head -n 1)" >> $GITHUB_OUTPUT
          
      - name: Create temporary admin service account
        run: |
          # Create the namespace if it doesn't exist
          kubectl get namespace ${{ env.KUBE_NAMESPACE }} || kubectl create namespace ${{ env.KUBE_NAMESPACE }}
          
          # Clean up any previous service accounts and bindings
          kubectl delete clusterrolebinding nginx-ingress-deployer-admin --ignore-not-found=true
          kubectl delete serviceaccount nginx-ingress-deployer-admin -n ${{ env.KUBE_NAMESPACE }} --ignore-not-found=true
          
          # Create new admin service account with cluster-admin role
          kubectl apply -f k8s/admin-service-account.yaml
          
          echo "Created temporary admin service account for deployment"
          kubectl get serviceaccount nginx-ingress-deployer-admin -n ${{ env.KUBE_NAMESPACE }}
          kubectl get clusterrolebinding nginx-ingress-deployer-admin

      - name: Deploy
        run: |
          ACTION="${{ github.event.inputs.action || 'apply' }}"
          IMAGE="${{ needs.build.outputs.image }}"
          RANDOM_SUFFIX="${{ steps.random.outputs.suffix }}"
          
          # Process the job yaml with environment variables
          cat k8s/deployment-job.yaml | \
            sed "s|IMAGE_PLACEHOLDER|$IMAGE|g" | \
            sed "s|ACTION_PLACEHOLDER|$ACTION|g" | \
            sed "s|RANDOM_PLACEHOLDER|$RANDOM_SUFFIX|g" | \
            kubectl apply -f -
          
          echo "Job deployed to cluster using service account"

      - name: Monitor
        run: |
          ACTION="${{ github.event.inputs.action || 'apply' }}"
          RANDOM_SUFFIX="${{ steps.random.outputs.suffix }}"
          JOB_NAME="nginx-ingress-deployment-$ACTION-$RANDOM_SUFFIX"
          
          echo "Waiting for job to complete..."
          # Use || true to prevent the workflow from failing if the job fails
          kubectl wait --for=condition=complete job/$JOB_NAME -n ${{ env.KUBE_NAMESPACE }} --timeout=900s || true
          
          # Debug: Check if job exists and show its full YAML
          echo "Job status:"
          kubectl get job/$JOB_NAME -n ${{ env.KUBE_NAMESPACE }} -o yaml || echo "Job not found"
          
          # Check if the job failed and get logs
          JOB_STATUS=$(kubectl get job/$JOB_NAME -n ${{ env.KUBE_NAMESPACE }} -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}')
          JOB_SUCCEEDED=$(kubectl get job/$JOB_NAME -n ${{ env.KUBE_NAMESPACE }} -o jsonpath='{.status.succeeded}')
          
          echo "Job logs:"
          kubectl logs job/$JOB_NAME -n ${{ env.KUBE_NAMESPACE }}
          
          if [ "$ACTION" = "apply" ]; then
            echo "Checking NGINX Ingress status..."
            kubectl get pods -n ingress-nginx || echo "No pods found in ingress-nginx namespace"
            kubectl get svc -n ingress-nginx || echo "No services found in ingress-nginx namespace"
          fi
          
          # If job succeeded, clean up the admin service account for security
          if [ "$JOB_SUCCEEDED" = "1" ]; then
            echo "Job completed successfully. Cleaning up temporary admin service account..."
            kubectl delete -f k8s/admin-service-account.yaml --ignore-not-found=true
            echo "Temporary admin service account removed for security"
          else
            echo "Job did not complete successfully. Leaving admin service account for debugging."
          fi
          
          # If job failed or appears to be stuck, provide detailed diagnostics
          if [ "$JOB_STATUS" == "True" ] || [ -z "$(kubectl get pods -n ${{ env.KUBE_NAMESPACE }} -l job-name=$JOB_NAME --field-selector=status.phase==Succeeded -o name)" ]; then
            echo "::error::Job failed or did not complete successfully. Getting additional debugging information..."
            
            echo "--- Job Status ---"
            kubectl describe job/$JOB_NAME -n ${{ env.KUBE_NAMESPACE }}
            
            echo "--- Pod Details ---"
            POD_NAME=$(kubectl get pods -n ${{ env.KUBE_NAMESPACE }} -l job-name=$JOB_NAME -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")
            if [ -n "$POD_NAME" ]; then
              kubectl describe pod $POD_NAME -n ${{ env.KUBE_NAMESPACE }}
              echo "--- Pod Logs ---"
              kubectl logs $POD_NAME -n ${{ env.KUBE_NAMESPACE }} --previous || echo "No previous logs available"
            else
              echo "No pods found for the job"
            fi
            
            if [ "$ACTION" = "apply" ]; then
              echo "--- NGINX Ingress Resources ---"
              kubectl get all -n ingress-nginx || echo "No resources found in ingress-nginx namespace"
            fi
            
            exit 1
          fi
