name: Deploy NGINX Ingress Controller

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/nginx-ingress-deployer
  KUBE_NAMESPACE: deployment-automation

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      
      - name: Set image output
        id: image
        run: echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          
      - name: Ensure service account exists with proper permissions
        run: |
          # Create the namespace if it doesn't exist
          kubectl get namespace ${{ env.KUBE_NAMESPACE }} || kubectl create namespace ${{ env.KUBE_NAMESPACE }}
          
          # Explicitly delete ClusterRole and ClusterRoleBinding first to ensure clean update
          kubectl delete clusterrole nginx-ingress-deployer --ignore-not-found=true
          kubectl delete clusterrolebinding nginx-ingress-deployer --ignore-not-found=true
          
          # Delete service account
          kubectl delete serviceaccount nginx-ingress-deployer -n ${{ env.KUBE_NAMESPACE }} --ignore-not-found=true
          
          # Apply the service account and RBAC configuration with updated permissions
          kubectl apply -f k8s/service-account.yaml
          
          # Verify the service account and RBAC resources exist
          echo "Verifying service account and RBAC resources..."
          kubectl get serviceaccount nginx-ingress-deployer -n ${{ env.KUBE_NAMESPACE }}
          kubectl get clusterrole nginx-ingress-deployer
          kubectl get clusterrolebinding nginx-ingress-deployer

      - name: Deploy
        run: |
          ACTION="${{ github.event.inputs.action || 'apply' }}"
          IMAGE="${{ needs.build.outputs.image }}"
          
          # Process the job yaml with environment variables
          cat k8s/deployment-job.yaml | \
            sed "s|IMAGE_PLACEHOLDER|$IMAGE|g" | \
            sed "s|ACTION_PLACEHOLDER|$ACTION|g" | \
            kubectl apply -f -
          
          echo "Job deployed to cluster using service account"

      - name: Monitor
        run: |
          ACTION="${{ github.event.inputs.action || 'apply' }}"
          
          echo "Waiting for job to complete..."
          # Use || true to prevent the workflow from failing if the job fails
          kubectl wait --for=condition=complete job/nginx-ingress-deployment-$ACTION -n ${{ env.KUBE_NAMESPACE }} --timeout=900s || true
          
          # Check if the job failed and get logs
          JOB_STATUS=$(kubectl get job/nginx-ingress-deployment-$ACTION -n ${{ env.KUBE_NAMESPACE }} -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}')
          
          echo "Job logs:"
          kubectl logs job/nginx-ingress-deployment-$ACTION -n ${{ env.KUBE_NAMESPACE }}
          
          if [ "$ACTION" = "apply" ]; then
            echo "Checking NGINX Ingress status..."
            kubectl get pods -n ingress-nginx || echo "No pods found in ingress-nginx namespace"
            kubectl get svc -n ingress-nginx || echo "No services found in ingress-nginx namespace"
          fi
          
          # If job failed or appears to be stuck, provide detailed diagnostics
          if [ "$JOB_STATUS" == "True" ] || [ -z "$(kubectl get pods -n ${{ env.KUBE_NAMESPACE }} -l job-name=nginx-ingress-deployment-$ACTION --field-selector=status.phase==Succeeded -o name)" ]; then
            echo "::error::Job failed or did not complete successfully. Getting additional debugging information..."
            
            echo "--- Job Status ---"
            kubectl describe job/nginx-ingress-deployment-$ACTION -n ${{ env.KUBE_NAMESPACE }}
            
            echo "--- Pod Details ---"
            POD_NAME=$(kubectl get pods -n ${{ env.KUBE_NAMESPACE }} -l job-name=nginx-ingress-deployment-$ACTION -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")
            if [ -n "$POD_NAME" ]; then
              kubectl describe pod $POD_NAME -n ${{ env.KUBE_NAMESPACE }}
              echo "--- Pod Logs ---"
              kubectl logs $POD_NAME -n ${{ env.KUBE_NAMESPACE }} --previous || echo "No previous logs available"
            else
              echo "No pods found for the job"
            fi
            
            if [ "$ACTION" = "apply" ]; then
              echo "--- NGINX Ingress Resources ---"
              kubectl get all -n ingress-nginx || echo "No resources found in ingress-nginx namespace"
            fi
            
            exit 1
          fi
